# Generated by Django 4.2.6 on 2023-10-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_utilisateur_user_utilisateur_groups_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='description',
            new_name='quick_description',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='full_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
